python3 -m pip install --upgrade pip
python3 -m pip install altgraph
python3 -m pip install asn1crypto
python3 -m pip install backports.functools-lru-cache
python3 -m pip install bcrypt
python3 -m pip install beautifulsoup4
python3 -m pip install certifi
python3 -m pip install cffi
python3 -m pip install chardet
python3 -m pip install Click
python3 -m pip install colorama
python3 -m pip install credentials
python3 -m pip install cryptography
python3 -m pip install cx-Oracle
python3 -m pip install dis3
python3 -m pip install Django
python3 -m pip install enum34
python3 -m pip install et-xmlfile
python3 -m pip install fire
python3 -m pip install future
python3 -m pip install gTTS
python3 -m pip install gTTS-token
python3 -m pip install idna
python3 -m pip install inflect
python3 -m pip install ipaddress
python3 -m pip install iso8601
python3 -m pip install jaraco.itertools
python3 -m pip install jdcal
python3 -m pip install more-itertools
python3 -m pip install mysql-connector
python3 -m pip install numpy
python3 -m pip install opencv-python==4.1.1.26
python3 -m pip install openpyxl
python3 -m pip install pandas
python3 -m pip install paramiko
python3 -m pip install pathlib
python3 -m pip install pefile
python3 -m pip install playsound
python3 -m pip install PyAudio
python3 -m pip install pycparser
python3 -m pip install PyInstaller
python3 -m pip install PyNaCl
python3 -m pip install pyOpenSSL
python3 -m pip install pyserial
python3 -m pip install python-dateutil
python3 -m pip install pyttsx
python3 -m pip install pytz
python3 -m pip install PyVISA
python3 -m pip install pywin32-ctypes
python3 -m pip install PyYAML
python3 -m pip install pyyml
python3 -m pip install requests
python3 -m pip install selenium
python3 -m pip uninstall serial
python3 -m pip install six
python3 -m pip install soupsieve
python3 -m pip install SpeechRecognition
python3 -m pip install termcolor
python3 -m pip install urllib3
python3 -m pip install utils
python3 -m pip install visa
python3 -m pip install wolframalpha
python3 -m pip install xlrd
python3 -m pip install XlsxWriter
python3 -m pip install xlwt
python3 -m pip install xmltodict
python3 -m pip install bleak
python3 -m pip install easygui
python3 -m pip install mysql-connector-python
python3 -m pip install --upgrade pip
